# Generated by Django 2.2.7 on 2019-12-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown', '?'), ('', '')], default='', help_text='Age', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(help_text='Date', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(choices=[('AM', 'Before Noon'), ('PM', 'After Noon')], default='AM', help_text='Shift', max_length=2, null=True),
        ),
    ]
